[package]
name = "zybil"
type = "contract"
authors = [""]
compiler_version = "0.16.0-aztec.1"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.8.14", directory="yarn-project/aztec-nr/aztec" }
address_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.8.14", directory="yarn-project/aztec-nr/address-note" }