[package]
name = "zybil"
type = "contract"
authors = [""]
compiler_version = "0.17.0-aztec.2"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.11.0", directory="yarn-project/aztec-nr/aztec" }
address_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.11.0", directory="yarn-project/aztec-nr/address-note" }